// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Application.proto

package com.fang.demo.rpc;

public final class SysApplicationInfo {
  private SysApplicationInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SysApplicationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SysApplication)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    long getId();

    /**
     * <code>int32 appType = 2;</code>
     * @return The appType.
     */
    int getAppType();

    /**
     * <code>string appName = 3;</code>
     * @return The appName.
     */
    java.lang.String getAppName();
    /**
     * <code>string appName = 3;</code>
     * @return The bytes for appName.
     */
    com.google.protobuf.ByteString
        getAppNameBytes();
  }
  /**
   * Protobuf type {@code SysApplication}
   */
  public static final class SysApplication extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SysApplication)
      SysApplicationOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SysApplication.newBuilder() to construct.
    private SysApplication(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SysApplication() {
      appName_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SysApplication();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SysApplication(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt64();
              break;
            }
            case 16: {

              appType_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              appName_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.fang.demo.rpc.SysApplicationInfo.internal_static_SysApplication_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.fang.demo.rpc.SysApplicationInfo.internal_static_SysApplication_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.fang.demo.rpc.SysApplicationInfo.SysApplication.class, com.fang.demo.rpc.SysApplicationInfo.SysApplication.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }

    public static final int APPTYPE_FIELD_NUMBER = 2;
    private int appType_;
    /**
     * <code>int32 appType = 2;</code>
     * @return The appType.
     */
    @java.lang.Override
    public int getAppType() {
      return appType_;
    }

    public static final int APPNAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object appName_;
    /**
     * <code>string appName = 3;</code>
     * @return The appName.
     */
    @java.lang.Override
    public java.lang.String getAppName() {
      java.lang.Object ref = appName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        appName_ = s;
        return s;
      }
    }
    /**
     * <code>string appName = 3;</code>
     * @return The bytes for appName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAppNameBytes() {
      java.lang.Object ref = appName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (appType_ != 0) {
        output.writeInt32(2, appType_);
      }
      if (!getAppNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, appName_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (appType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, appType_);
      }
      if (!getAppNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, appName_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.fang.demo.rpc.SysApplicationInfo.SysApplication)) {
        return super.equals(obj);
      }
      com.fang.demo.rpc.SysApplicationInfo.SysApplication other = (com.fang.demo.rpc.SysApplicationInfo.SysApplication) obj;

      if (getId()
          != other.getId()) return false;
      if (getAppType()
          != other.getAppType()) return false;
      if (!getAppName()
          .equals(other.getAppName())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + APPTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getAppType();
      hash = (37 * hash) + APPNAME_FIELD_NUMBER;
      hash = (53 * hash) + getAppName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.fang.demo.rpc.SysApplicationInfo.SysApplication parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fang.demo.rpc.SysApplicationInfo.SysApplication parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fang.demo.rpc.SysApplicationInfo.SysApplication parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fang.demo.rpc.SysApplicationInfo.SysApplication parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fang.demo.rpc.SysApplicationInfo.SysApplication parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fang.demo.rpc.SysApplicationInfo.SysApplication parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fang.demo.rpc.SysApplicationInfo.SysApplication parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fang.demo.rpc.SysApplicationInfo.SysApplication parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fang.demo.rpc.SysApplicationInfo.SysApplication parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.fang.demo.rpc.SysApplicationInfo.SysApplication parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fang.demo.rpc.SysApplicationInfo.SysApplication parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fang.demo.rpc.SysApplicationInfo.SysApplication parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.fang.demo.rpc.SysApplicationInfo.SysApplication prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SysApplication}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SysApplication)
        com.fang.demo.rpc.SysApplicationInfo.SysApplicationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.fang.demo.rpc.SysApplicationInfo.internal_static_SysApplication_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.fang.demo.rpc.SysApplicationInfo.internal_static_SysApplication_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.fang.demo.rpc.SysApplicationInfo.SysApplication.class, com.fang.demo.rpc.SysApplicationInfo.SysApplication.Builder.class);
      }

      // Construct using com.fang.demo.rpc.SysApplicationInfo.SysApplication.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0L;

        appType_ = 0;

        appName_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.fang.demo.rpc.SysApplicationInfo.internal_static_SysApplication_descriptor;
      }

      @java.lang.Override
      public com.fang.demo.rpc.SysApplicationInfo.SysApplication getDefaultInstanceForType() {
        return com.fang.demo.rpc.SysApplicationInfo.SysApplication.getDefaultInstance();
      }

      @java.lang.Override
      public com.fang.demo.rpc.SysApplicationInfo.SysApplication build() {
        com.fang.demo.rpc.SysApplicationInfo.SysApplication result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.fang.demo.rpc.SysApplicationInfo.SysApplication buildPartial() {
        com.fang.demo.rpc.SysApplicationInfo.SysApplication result = new com.fang.demo.rpc.SysApplicationInfo.SysApplication(this);
        result.id_ = id_;
        result.appType_ = appType_;
        result.appName_ = appName_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.fang.demo.rpc.SysApplicationInfo.SysApplication) {
          return mergeFrom((com.fang.demo.rpc.SysApplicationInfo.SysApplication)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.fang.demo.rpc.SysApplicationInfo.SysApplication other) {
        if (other == com.fang.demo.rpc.SysApplicationInfo.SysApplication.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (other.getAppType() != 0) {
          setAppType(other.getAppType());
        }
        if (!other.getAppName().isEmpty()) {
          appName_ = other.appName_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.fang.demo.rpc.SysApplicationInfo.SysApplication parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.fang.demo.rpc.SysApplicationInfo.SysApplication) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long id_ ;
      /**
       * <code>int64 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private int appType_ ;
      /**
       * <code>int32 appType = 2;</code>
       * @return The appType.
       */
      @java.lang.Override
      public int getAppType() {
        return appType_;
      }
      /**
       * <code>int32 appType = 2;</code>
       * @param value The appType to set.
       * @return This builder for chaining.
       */
      public Builder setAppType(int value) {
        
        appType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 appType = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAppType() {
        
        appType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object appName_ = "";
      /**
       * <code>string appName = 3;</code>
       * @return The appName.
       */
      public java.lang.String getAppName() {
        java.lang.Object ref = appName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          appName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string appName = 3;</code>
       * @return The bytes for appName.
       */
      public com.google.protobuf.ByteString
          getAppNameBytes() {
        java.lang.Object ref = appName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          appName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string appName = 3;</code>
       * @param value The appName to set.
       * @return This builder for chaining.
       */
      public Builder setAppName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        appName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string appName = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearAppName() {
        
        appName_ = getDefaultInstance().getAppName();
        onChanged();
        return this;
      }
      /**
       * <code>string appName = 3;</code>
       * @param value The bytes for appName to set.
       * @return This builder for chaining.
       */
      public Builder setAppNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        appName_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:SysApplication)
    }

    // @@protoc_insertion_point(class_scope:SysApplication)
    private static final com.fang.demo.rpc.SysApplicationInfo.SysApplication DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.fang.demo.rpc.SysApplicationInfo.SysApplication();
    }

    public static com.fang.demo.rpc.SysApplicationInfo.SysApplication getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SysApplication>
        PARSER = new com.google.protobuf.AbstractParser<SysApplication>() {
      @java.lang.Override
      public SysApplication parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SysApplication(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SysApplication> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SysApplication> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.fang.demo.rpc.SysApplicationInfo.SysApplication getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetAllAppInfoListRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GetAllAppInfoListRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();
  }
  /**
   * Protobuf type {@code GetAllAppInfoListRequest}
   */
  public static final class GetAllAppInfoListRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GetAllAppInfoListRequest)
      GetAllAppInfoListRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetAllAppInfoListRequest.newBuilder() to construct.
    private GetAllAppInfoListRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetAllAppInfoListRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GetAllAppInfoListRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GetAllAppInfoListRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.fang.demo.rpc.SysApplicationInfo.internal_static_GetAllAppInfoListRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.fang.demo.rpc.SysApplicationInfo.internal_static_GetAllAppInfoListRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.fang.demo.rpc.SysApplicationInfo.GetAllAppInfoListRequest.class, com.fang.demo.rpc.SysApplicationInfo.GetAllAppInfoListRequest.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.fang.demo.rpc.SysApplicationInfo.GetAllAppInfoListRequest)) {
        return super.equals(obj);
      }
      com.fang.demo.rpc.SysApplicationInfo.GetAllAppInfoListRequest other = (com.fang.demo.rpc.SysApplicationInfo.GetAllAppInfoListRequest) obj;

      if (getId()
          != other.getId()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.fang.demo.rpc.SysApplicationInfo.GetAllAppInfoListRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fang.demo.rpc.SysApplicationInfo.GetAllAppInfoListRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fang.demo.rpc.SysApplicationInfo.GetAllAppInfoListRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fang.demo.rpc.SysApplicationInfo.GetAllAppInfoListRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fang.demo.rpc.SysApplicationInfo.GetAllAppInfoListRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fang.demo.rpc.SysApplicationInfo.GetAllAppInfoListRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fang.demo.rpc.SysApplicationInfo.GetAllAppInfoListRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fang.demo.rpc.SysApplicationInfo.GetAllAppInfoListRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fang.demo.rpc.SysApplicationInfo.GetAllAppInfoListRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.fang.demo.rpc.SysApplicationInfo.GetAllAppInfoListRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fang.demo.rpc.SysApplicationInfo.GetAllAppInfoListRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fang.demo.rpc.SysApplicationInfo.GetAllAppInfoListRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.fang.demo.rpc.SysApplicationInfo.GetAllAppInfoListRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GetAllAppInfoListRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GetAllAppInfoListRequest)
        com.fang.demo.rpc.SysApplicationInfo.GetAllAppInfoListRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.fang.demo.rpc.SysApplicationInfo.internal_static_GetAllAppInfoListRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.fang.demo.rpc.SysApplicationInfo.internal_static_GetAllAppInfoListRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.fang.demo.rpc.SysApplicationInfo.GetAllAppInfoListRequest.class, com.fang.demo.rpc.SysApplicationInfo.GetAllAppInfoListRequest.Builder.class);
      }

      // Construct using com.fang.demo.rpc.SysApplicationInfo.GetAllAppInfoListRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.fang.demo.rpc.SysApplicationInfo.internal_static_GetAllAppInfoListRequest_descriptor;
      }

      @java.lang.Override
      public com.fang.demo.rpc.SysApplicationInfo.GetAllAppInfoListRequest getDefaultInstanceForType() {
        return com.fang.demo.rpc.SysApplicationInfo.GetAllAppInfoListRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.fang.demo.rpc.SysApplicationInfo.GetAllAppInfoListRequest build() {
        com.fang.demo.rpc.SysApplicationInfo.GetAllAppInfoListRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.fang.demo.rpc.SysApplicationInfo.GetAllAppInfoListRequest buildPartial() {
        com.fang.demo.rpc.SysApplicationInfo.GetAllAppInfoListRequest result = new com.fang.demo.rpc.SysApplicationInfo.GetAllAppInfoListRequest(this);
        result.id_ = id_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.fang.demo.rpc.SysApplicationInfo.GetAllAppInfoListRequest) {
          return mergeFrom((com.fang.demo.rpc.SysApplicationInfo.GetAllAppInfoListRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.fang.demo.rpc.SysApplicationInfo.GetAllAppInfoListRequest other) {
        if (other == com.fang.demo.rpc.SysApplicationInfo.GetAllAppInfoListRequest.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.fang.demo.rpc.SysApplicationInfo.GetAllAppInfoListRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.fang.demo.rpc.SysApplicationInfo.GetAllAppInfoListRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:GetAllAppInfoListRequest)
    }

    // @@protoc_insertion_point(class_scope:GetAllAppInfoListRequest)
    private static final com.fang.demo.rpc.SysApplicationInfo.GetAllAppInfoListRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.fang.demo.rpc.SysApplicationInfo.GetAllAppInfoListRequest();
    }

    public static com.fang.demo.rpc.SysApplicationInfo.GetAllAppInfoListRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetAllAppInfoListRequest>
        PARSER = new com.google.protobuf.AbstractParser<GetAllAppInfoListRequest>() {
      @java.lang.Override
      public GetAllAppInfoListRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetAllAppInfoListRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetAllAppInfoListRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetAllAppInfoListRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.fang.demo.rpc.SysApplicationInfo.GetAllAppInfoListRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetAllAppInfoListResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GetAllAppInfoListResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool success = 1;</code>
     * @return The success.
     */
    boolean getSuccess();

    /**
     * <code>int32 code = 2;</code>
     * @return The code.
     */
    int getCode();

    /**
     * <code>string msg = 3;</code>
     * @return The msg.
     */
    java.lang.String getMsg();
    /**
     * <code>string msg = 3;</code>
     * @return The bytes for msg.
     */
    com.google.protobuf.ByteString
        getMsgBytes();

    /**
     * <code>.SysApplication appInfo = 4;</code>
     * @return Whether the appInfo field is set.
     */
    boolean hasAppInfo();
    /**
     * <code>.SysApplication appInfo = 4;</code>
     * @return The appInfo.
     */
    com.fang.demo.rpc.SysApplicationInfo.SysApplication getAppInfo();
    /**
     * <code>.SysApplication appInfo = 4;</code>
     */
    com.fang.demo.rpc.SysApplicationInfo.SysApplicationOrBuilder getAppInfoOrBuilder();
  }
  /**
   * Protobuf type {@code GetAllAppInfoListResponse}
   */
  public static final class GetAllAppInfoListResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GetAllAppInfoListResponse)
      GetAllAppInfoListResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetAllAppInfoListResponse.newBuilder() to construct.
    private GetAllAppInfoListResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetAllAppInfoListResponse() {
      msg_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GetAllAppInfoListResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GetAllAppInfoListResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              success_ = input.readBool();
              break;
            }
            case 16: {

              code_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              msg_ = s;
              break;
            }
            case 34: {
              com.fang.demo.rpc.SysApplicationInfo.SysApplication.Builder subBuilder = null;
              if (appInfo_ != null) {
                subBuilder = appInfo_.toBuilder();
              }
              appInfo_ = input.readMessage(com.fang.demo.rpc.SysApplicationInfo.SysApplication.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(appInfo_);
                appInfo_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.fang.demo.rpc.SysApplicationInfo.internal_static_GetAllAppInfoListResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.fang.demo.rpc.SysApplicationInfo.internal_static_GetAllAppInfoListResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.fang.demo.rpc.SysApplicationInfo.GetAllAppInfoListResponse.class, com.fang.demo.rpc.SysApplicationInfo.GetAllAppInfoListResponse.Builder.class);
    }

    public static final int SUCCESS_FIELD_NUMBER = 1;
    private boolean success_;
    /**
     * <code>bool success = 1;</code>
     * @return The success.
     */
    @java.lang.Override
    public boolean getSuccess() {
      return success_;
    }

    public static final int CODE_FIELD_NUMBER = 2;
    private int code_;
    /**
     * <code>int32 code = 2;</code>
     * @return The code.
     */
    @java.lang.Override
    public int getCode() {
      return code_;
    }

    public static final int MSG_FIELD_NUMBER = 3;
    private volatile java.lang.Object msg_;
    /**
     * <code>string msg = 3;</code>
     * @return The msg.
     */
    @java.lang.Override
    public java.lang.String getMsg() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msg_ = s;
        return s;
      }
    }
    /**
     * <code>string msg = 3;</code>
     * @return The bytes for msg.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMsgBytes() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int APPINFO_FIELD_NUMBER = 4;
    private com.fang.demo.rpc.SysApplicationInfo.SysApplication appInfo_;
    /**
     * <code>.SysApplication appInfo = 4;</code>
     * @return Whether the appInfo field is set.
     */
    @java.lang.Override
    public boolean hasAppInfo() {
      return appInfo_ != null;
    }
    /**
     * <code>.SysApplication appInfo = 4;</code>
     * @return The appInfo.
     */
    @java.lang.Override
    public com.fang.demo.rpc.SysApplicationInfo.SysApplication getAppInfo() {
      return appInfo_ == null ? com.fang.demo.rpc.SysApplicationInfo.SysApplication.getDefaultInstance() : appInfo_;
    }
    /**
     * <code>.SysApplication appInfo = 4;</code>
     */
    @java.lang.Override
    public com.fang.demo.rpc.SysApplicationInfo.SysApplicationOrBuilder getAppInfoOrBuilder() {
      return getAppInfo();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (success_ != false) {
        output.writeBool(1, success_);
      }
      if (code_ != 0) {
        output.writeInt32(2, code_);
      }
      if (!getMsgBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, msg_);
      }
      if (appInfo_ != null) {
        output.writeMessage(4, getAppInfo());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (success_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, success_);
      }
      if (code_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, code_);
      }
      if (!getMsgBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, msg_);
      }
      if (appInfo_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getAppInfo());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.fang.demo.rpc.SysApplicationInfo.GetAllAppInfoListResponse)) {
        return super.equals(obj);
      }
      com.fang.demo.rpc.SysApplicationInfo.GetAllAppInfoListResponse other = (com.fang.demo.rpc.SysApplicationInfo.GetAllAppInfoListResponse) obj;

      if (getSuccess()
          != other.getSuccess()) return false;
      if (getCode()
          != other.getCode()) return false;
      if (!getMsg()
          .equals(other.getMsg())) return false;
      if (hasAppInfo() != other.hasAppInfo()) return false;
      if (hasAppInfo()) {
        if (!getAppInfo()
            .equals(other.getAppInfo())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getSuccess());
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCode();
      hash = (37 * hash) + MSG_FIELD_NUMBER;
      hash = (53 * hash) + getMsg().hashCode();
      if (hasAppInfo()) {
        hash = (37 * hash) + APPINFO_FIELD_NUMBER;
        hash = (53 * hash) + getAppInfo().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.fang.demo.rpc.SysApplicationInfo.GetAllAppInfoListResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fang.demo.rpc.SysApplicationInfo.GetAllAppInfoListResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fang.demo.rpc.SysApplicationInfo.GetAllAppInfoListResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fang.demo.rpc.SysApplicationInfo.GetAllAppInfoListResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fang.demo.rpc.SysApplicationInfo.GetAllAppInfoListResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fang.demo.rpc.SysApplicationInfo.GetAllAppInfoListResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fang.demo.rpc.SysApplicationInfo.GetAllAppInfoListResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fang.demo.rpc.SysApplicationInfo.GetAllAppInfoListResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fang.demo.rpc.SysApplicationInfo.GetAllAppInfoListResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.fang.demo.rpc.SysApplicationInfo.GetAllAppInfoListResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fang.demo.rpc.SysApplicationInfo.GetAllAppInfoListResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fang.demo.rpc.SysApplicationInfo.GetAllAppInfoListResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.fang.demo.rpc.SysApplicationInfo.GetAllAppInfoListResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GetAllAppInfoListResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GetAllAppInfoListResponse)
        com.fang.demo.rpc.SysApplicationInfo.GetAllAppInfoListResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.fang.demo.rpc.SysApplicationInfo.internal_static_GetAllAppInfoListResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.fang.demo.rpc.SysApplicationInfo.internal_static_GetAllAppInfoListResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.fang.demo.rpc.SysApplicationInfo.GetAllAppInfoListResponse.class, com.fang.demo.rpc.SysApplicationInfo.GetAllAppInfoListResponse.Builder.class);
      }

      // Construct using com.fang.demo.rpc.SysApplicationInfo.GetAllAppInfoListResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        success_ = false;

        code_ = 0;

        msg_ = "";

        if (appInfoBuilder_ == null) {
          appInfo_ = null;
        } else {
          appInfo_ = null;
          appInfoBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.fang.demo.rpc.SysApplicationInfo.internal_static_GetAllAppInfoListResponse_descriptor;
      }

      @java.lang.Override
      public com.fang.demo.rpc.SysApplicationInfo.GetAllAppInfoListResponse getDefaultInstanceForType() {
        return com.fang.demo.rpc.SysApplicationInfo.GetAllAppInfoListResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.fang.demo.rpc.SysApplicationInfo.GetAllAppInfoListResponse build() {
        com.fang.demo.rpc.SysApplicationInfo.GetAllAppInfoListResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.fang.demo.rpc.SysApplicationInfo.GetAllAppInfoListResponse buildPartial() {
        com.fang.demo.rpc.SysApplicationInfo.GetAllAppInfoListResponse result = new com.fang.demo.rpc.SysApplicationInfo.GetAllAppInfoListResponse(this);
        result.success_ = success_;
        result.code_ = code_;
        result.msg_ = msg_;
        if (appInfoBuilder_ == null) {
          result.appInfo_ = appInfo_;
        } else {
          result.appInfo_ = appInfoBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.fang.demo.rpc.SysApplicationInfo.GetAllAppInfoListResponse) {
          return mergeFrom((com.fang.demo.rpc.SysApplicationInfo.GetAllAppInfoListResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.fang.demo.rpc.SysApplicationInfo.GetAllAppInfoListResponse other) {
        if (other == com.fang.demo.rpc.SysApplicationInfo.GetAllAppInfoListResponse.getDefaultInstance()) return this;
        if (other.getSuccess() != false) {
          setSuccess(other.getSuccess());
        }
        if (other.getCode() != 0) {
          setCode(other.getCode());
        }
        if (!other.getMsg().isEmpty()) {
          msg_ = other.msg_;
          onChanged();
        }
        if (other.hasAppInfo()) {
          mergeAppInfo(other.getAppInfo());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.fang.demo.rpc.SysApplicationInfo.GetAllAppInfoListResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.fang.demo.rpc.SysApplicationInfo.GetAllAppInfoListResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean success_ ;
      /**
       * <code>bool success = 1;</code>
       * @return The success.
       */
      @java.lang.Override
      public boolean getSuccess() {
        return success_;
      }
      /**
       * <code>bool success = 1;</code>
       * @param value The success to set.
       * @return This builder for chaining.
       */
      public Builder setSuccess(boolean value) {
        
        success_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool success = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSuccess() {
        
        success_ = false;
        onChanged();
        return this;
      }

      private int code_ ;
      /**
       * <code>int32 code = 2;</code>
       * @return The code.
       */
      @java.lang.Override
      public int getCode() {
        return code_;
      }
      /**
       * <code>int32 code = 2;</code>
       * @param value The code to set.
       * @return This builder for chaining.
       */
      public Builder setCode(int value) {
        
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 code = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCode() {
        
        code_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object msg_ = "";
      /**
       * <code>string msg = 3;</code>
       * @return The msg.
       */
      public java.lang.String getMsg() {
        java.lang.Object ref = msg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          msg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string msg = 3;</code>
       * @return The bytes for msg.
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        java.lang.Object ref = msg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string msg = 3;</code>
       * @param value The msg to set.
       * @return This builder for chaining.
       */
      public Builder setMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string msg = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsg() {
        
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      /**
       * <code>string msg = 3;</code>
       * @param value The bytes for msg to set.
       * @return This builder for chaining.
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        msg_ = value;
        onChanged();
        return this;
      }

      private com.fang.demo.rpc.SysApplicationInfo.SysApplication appInfo_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.fang.demo.rpc.SysApplicationInfo.SysApplication, com.fang.demo.rpc.SysApplicationInfo.SysApplication.Builder, com.fang.demo.rpc.SysApplicationInfo.SysApplicationOrBuilder> appInfoBuilder_;
      /**
       * <code>.SysApplication appInfo = 4;</code>
       * @return Whether the appInfo field is set.
       */
      public boolean hasAppInfo() {
        return appInfoBuilder_ != null || appInfo_ != null;
      }
      /**
       * <code>.SysApplication appInfo = 4;</code>
       * @return The appInfo.
       */
      public com.fang.demo.rpc.SysApplicationInfo.SysApplication getAppInfo() {
        if (appInfoBuilder_ == null) {
          return appInfo_ == null ? com.fang.demo.rpc.SysApplicationInfo.SysApplication.getDefaultInstance() : appInfo_;
        } else {
          return appInfoBuilder_.getMessage();
        }
      }
      /**
       * <code>.SysApplication appInfo = 4;</code>
       */
      public Builder setAppInfo(com.fang.demo.rpc.SysApplicationInfo.SysApplication value) {
        if (appInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          appInfo_ = value;
          onChanged();
        } else {
          appInfoBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.SysApplication appInfo = 4;</code>
       */
      public Builder setAppInfo(
          com.fang.demo.rpc.SysApplicationInfo.SysApplication.Builder builderForValue) {
        if (appInfoBuilder_ == null) {
          appInfo_ = builderForValue.build();
          onChanged();
        } else {
          appInfoBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.SysApplication appInfo = 4;</code>
       */
      public Builder mergeAppInfo(com.fang.demo.rpc.SysApplicationInfo.SysApplication value) {
        if (appInfoBuilder_ == null) {
          if (appInfo_ != null) {
            appInfo_ =
              com.fang.demo.rpc.SysApplicationInfo.SysApplication.newBuilder(appInfo_).mergeFrom(value).buildPartial();
          } else {
            appInfo_ = value;
          }
          onChanged();
        } else {
          appInfoBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.SysApplication appInfo = 4;</code>
       */
      public Builder clearAppInfo() {
        if (appInfoBuilder_ == null) {
          appInfo_ = null;
          onChanged();
        } else {
          appInfo_ = null;
          appInfoBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.SysApplication appInfo = 4;</code>
       */
      public com.fang.demo.rpc.SysApplicationInfo.SysApplication.Builder getAppInfoBuilder() {
        
        onChanged();
        return getAppInfoFieldBuilder().getBuilder();
      }
      /**
       * <code>.SysApplication appInfo = 4;</code>
       */
      public com.fang.demo.rpc.SysApplicationInfo.SysApplicationOrBuilder getAppInfoOrBuilder() {
        if (appInfoBuilder_ != null) {
          return appInfoBuilder_.getMessageOrBuilder();
        } else {
          return appInfo_ == null ?
              com.fang.demo.rpc.SysApplicationInfo.SysApplication.getDefaultInstance() : appInfo_;
        }
      }
      /**
       * <code>.SysApplication appInfo = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.fang.demo.rpc.SysApplicationInfo.SysApplication, com.fang.demo.rpc.SysApplicationInfo.SysApplication.Builder, com.fang.demo.rpc.SysApplicationInfo.SysApplicationOrBuilder> 
          getAppInfoFieldBuilder() {
        if (appInfoBuilder_ == null) {
          appInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.fang.demo.rpc.SysApplicationInfo.SysApplication, com.fang.demo.rpc.SysApplicationInfo.SysApplication.Builder, com.fang.demo.rpc.SysApplicationInfo.SysApplicationOrBuilder>(
                  getAppInfo(),
                  getParentForChildren(),
                  isClean());
          appInfo_ = null;
        }
        return appInfoBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:GetAllAppInfoListResponse)
    }

    // @@protoc_insertion_point(class_scope:GetAllAppInfoListResponse)
    private static final com.fang.demo.rpc.SysApplicationInfo.GetAllAppInfoListResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.fang.demo.rpc.SysApplicationInfo.GetAllAppInfoListResponse();
    }

    public static com.fang.demo.rpc.SysApplicationInfo.GetAllAppInfoListResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetAllAppInfoListResponse>
        PARSER = new com.google.protobuf.AbstractParser<GetAllAppInfoListResponse>() {
      @java.lang.Override
      public GetAllAppInfoListResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetAllAppInfoListResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetAllAppInfoListResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetAllAppInfoListResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.fang.demo.rpc.SysApplicationInfo.GetAllAppInfoListResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SysApplication_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SysApplication_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetAllAppInfoListRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetAllAppInfoListRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetAllAppInfoListResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetAllAppInfoListResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021Application.proto\">\n\016SysApplication\022\n\n" +
      "\002id\030\001 \001(\003\022\017\n\007appType\030\002 \001(\005\022\017\n\007appName\030\003 " +
      "\001(\t\"&\n\030GetAllAppInfoListRequest\022\n\n\002id\030\001 " +
      "\001(\005\"i\n\031GetAllAppInfoListResponse\022\017\n\007succ" +
      "ess\030\001 \001(\010\022\014\n\004code\030\002 \001(\005\022\013\n\003msg\030\003 \001(\t\022 \n\007" +
      "appInfo\030\004 \001(\0132\017.SysApplication2e\n\025SysApp" +
      "licationService\022L\n\021getAllAppInfoList\022\031.G" +
      "etAllAppInfoListRequest\032\032.GetAllAppInfoL" +
      "istResponse\"\000B)\n\021com.fang.demo.rpcB\022SysA" +
      "pplicationInfoP\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_SysApplication_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SysApplication_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SysApplication_descriptor,
        new java.lang.String[] { "Id", "AppType", "AppName", });
    internal_static_GetAllAppInfoListRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GetAllAppInfoListRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetAllAppInfoListRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_GetAllAppInfoListResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_GetAllAppInfoListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetAllAppInfoListResponse_descriptor,
        new java.lang.String[] { "Success", "Code", "Msg", "AppInfo", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
