server:
  port: 59120

fang:
  yao:
    hui:
      name: "fangyaohui"

spring:
  application:
    name: com-fang-demo-grpcDemoUse
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: ${NACOS_HOST:localhost}:${NACOS_PORT:8849}
        namespace: dev
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        namespace: dev
        refresh-enabled: true
        extension-configs:
          - data-id: com-fang-demo-grpcDemoUse-dev.yml
            refresh: true
        enable-remote-sync-config: true
  config:
    import:
      - optional:nacos:application-dev.yml
      - optional:nacos:${spring.application.name}-dev.yml

board:
  gov:
    mdm:
      sync:
        enabled: true
        serverAddr: "127.0.0.1:65123"