
server:
  port: 64961

spring:
  application:
    name: com-fang-demo-nacos
  cloud:
    nacos:
      discovery:
        username: nacos
        password: nacos
        server-addr: localhost:8849
        namespace: public
#  config:
#    import:
#      - optional:nacos:application-dev.yml
#      - optional:nacos:${spring.application.name}-dev.yml
